# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"$\n\x10\x66ragment_request\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"T\n\x15get_fragments_request\x12\x11\n\tfilenames\x18\x01 \x03(\t\x12\x14\n\x0cmax_erasures\x18\x02 \x01(\x05\x12\x12\n\nrequest_id\x18\x03 \x01(\t\"J\n\x11\x66ragments_reponse\x12\x11\n\tfilenames\x18\x01 \x03(\t\x12\x0e\n\x06\x63hunks\x18\x02 \x03(\x0c\x12\x12\n\nrequest_id\x18\x03 \x01(\t\"t\n\x10\x64\x65legate_request\x12\x11\n\tfilenames\x18\x01 \x03(\t\x12\x14\n\x0cmax_erasures\x18\x02 \x01(\x05\x12\x11\n\tfile_size\x18\x03 \x01(\x05\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\x08\x12\x12\n\nrequest_id\x18\x05 \x01(\t\"\'\n\x11\x64\x65legate_response\x12\x12\n\nrequest_id\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FRAGMENT_REQUEST._serialized_start=18
  _FRAGMENT_REQUEST._serialized_end=54
  _GET_FRAGMENTS_REQUEST._serialized_start=56
  _GET_FRAGMENTS_REQUEST._serialized_end=140
  _FRAGMENTS_REPONSE._serialized_start=142
  _FRAGMENTS_REPONSE._serialized_end=216
  _DELEGATE_REQUEST._serialized_start=218
  _DELEGATE_REQUEST._serialized_end=334
  _DELEGATE_RESPONSE._serialized_start=336
  _DELEGATE_RESPONSE._serialized_end=375
# @@protoc_insertion_point(module_scope)
